### PR TITLE
Updated `composer.json` ( Updated phpunit version ).

### PR DESCRIPTION
**Pull request by wotta**
Updated the phpunit composer version to use the `~7.0` version.

### CODE REVIEW

**Comment by wotta** [comment]
@armandsar could you please take a look at this? 🙂

**Comment by armandsar** [comment]
Any reason to do this?
I am using it on project stuck on laravel 5.2 version

**Comment by wotta** [comment]
Well because I use your project in a package of mine which supports 5.6.
Maybe merge this into a specific 5.6 branch? that way you don't get conflicts.

**Comment by armandsar** [comment]
Would this work for you?
`"phpunit/phpunit": "~6.0||~7.0"`

**Comment by wotta** [comment]
@armandsar Think that could help 🙂 will try that!

**Comment by wotta** [comment]
@armandsar fixed it 🙂

**Comment by armandsar** [comment]
Thanks, but I think we can safely leave laravel version as "~5.1", that would work for all

**Comment by wotta** [comment]
yeah, that could also be done, will fix that.

**Comment by armandsar** [comment]
@wotta Thanks! By the way - what package are you building?

**Comment by wotta** [comment]
@armandsar I am building a package which has useful commands that I normally use for laravel.
For example, a resource controller generator which fills in all functions so I don't need to do that.

In that example, I also use your package so I don't need to figure out the path to the view.

**Pull request merged**
